In [4]:
# Código creado por Joshua Mijangos López, 12/01/25
# Este código está hecho para que las matrices a las que se le aplicará el método se modifiquen desde aquí
# Este código no acepta datos de ingreso desde consola

import numpy as np

def lu_factorization(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Paso 1: Calcular elementos de U en la fila i
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # Paso 2: Calcular elementos de L en la columna i
        for j in range(i, n):
            if i == j:
                L[i, i] = 1  # Elementos de la diagonal de L son 1
            else:
                L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

# Matriz A del ejemplo 2
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

# Verificar factorización LU
L, U = lu_factorization(A)

# Mostrar resultados
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Verificación: L @ U debe ser igual a A
print("\nVerificación (L @ U):")
print(np.dot(L, U))

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Verificación (L @ U):
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
