**Tutorial de NumPy :D**

**Creado por Joshua Mijangos López, 05/11/24**

1. **Introducción a NumPy.**

NumPy es una biblioteca esencial para el cálculo científico en Python. Su nombre proviene de "*Numerical Python*". NumPy permite realizar cálculos numéricos y manipulación de datos de manera eficiente mediante arreglos y matrices, los cuales son más rápidos y fáciles de manejar que las listas estándar de Python.


*   Ventajas: En comparación con las listas, los arreglos de NumPy ocupan menos memoria y permiten realizar operaciones matemáticas complejas de manera directa, gracias a sus funciones optimizadas
*   Objetivo: En este tutorial, aprenderemos a trabajar con arreglos y funciones de NumPy, útiles para análisis de datos, interpolación y graficación.

1.1. *Instalación.*

Esta es la forma más común de instalar numpy, ya que pip viene preinstalado con Python.

Abre una terminal o línea de comandos y ejecuta el siguiente comando:



In [ ]:
pip install numpy

Si por alguna razón necesitas instalar numpy desde su código fuente, puedes seguir estos pasos:

1) Clona el repositorio de numpy desde GitHub:



In [ ]:
git clone https://github.com/numpy/numpy.git

2) Ve al directorio de numpy:

In [ ]:
cd numpy

3) Compila e instala numpy:

In [ ]:
python setup.py install

Una vez instalado, puedes verificar la instalación abriendo un intérprete de Python y ejecutando:

In [ ]:
import numpy
print (numpy.__version__)

2. **Arreglos de NumPy.**

En NumPy, los arreglos (arrays) son estructuras de datos de múltiples dimensiones (1D, 2D, etc.) que contienen elementos de un tipo específico (como int, float). Son similares a las listas en Python, pero están optimizados para realizar operaciones matemáticas y de datos con mayor velocidad y menor consumo de memoria.

2.1 *Creación de Arreglos*:

* **np.array()**: Permite crear un arreglo a partir de una lista o lista de listas. Es el método más común para crear arreglos con datos específicos.
Arreglos de Ceros, Unos y Vacias:

* **np.zeros(dimensiones) y np.ones(dimensiones)**: Generan arreglos llenos de ceros o unos, respectivamente, y son útiles para inicializar datos.

* **np.empty(dimensiones)**: Genera un arreglo vacío (sin inicializar los valores). Es más rápido pero debe usarse con cuidado, ya que contiene valores aleatorios hasta que se les asignen datos específicos.

2.2 *Arreglos de Números Enteros y Flotantes*:

* **dtype**: Al crear un arreglo, podemos especificar su tipo de datos con el parámetro dtype. Esto ayuda a optimizar la memoria cuando solo se necesitan ciertos tipos, como enteros de 8 bits (int8) o flotantes de 32 bits (float32).

2.3 *Ejemplos:*




In [7]:
import numpy as np

# Crear un arreglo unidimensional
a = np.array([1, 2, 3, 4])
print("Arreglo unidimensional:", a)

Arreglo unidimensional: [1 2 3 4]


In [8]:
# Crear un arreglo bidimensional
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Arreglo bidimensional:\n", b)

Arreglo bidimensional:
 [[1 2 3]
 [4 5 6]]


In [9]:
# Crear un arreglo de unos con dimensiones (3, 3)
c = np.ones((3, 3))
print("Arreglo de unos:\n", c)

Arreglo de unos:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Crear un arreglo de números enteros con dtype específico
d = np.array([1, 2, 3], dtype=np.int8)
print("Arreglo con tipo de datos int8:", d)

Arreglo con tipo de datos int8: [1 2 3]


3. **Funciones Básicas de NumPy**

NumPy provee funciones matemáticas básicas que operan en los arreglos de forma vectorizada, es decir, se aplican de manera eficiente sobre cada elemento del arreglo sin la necesidad de usar bucles explícitos en Python.

3.1 *Atributos del Arreglo:*

Los atributos en NumPy permiten obtener información importante sobre los arreglos, como su tamaño, forma y tipo de datos, lo que ayuda a saber cómo están organizados y cuál es su capacidad de almacenamiento y cálculo. A continuación, se explican algunos de los atributos básicos de un arreglo:


*   **ndim**: Representa el número de dimensiones (o ejes) del arreglo. Los arreglos unidimensionales (ndim=1) son similares a listas, mientras que los arreglos bidimensionales (ndim=2) se asemejan a matrices, y los arreglos de mayor dimensión (ndim>2) se usan en procesamiento de datos más complejo, como en aprendizaje profundo.

*  **shape**: Indica la forma del arreglo, es decir, el tamaño a lo largo de cada dimensión. Si tienes un arreglo bidimensional, shape será una tupla que representa el número de filas y columnas del arreglo.

*   **size**: Es el número total de elementos en el arreglo. Este valor es el producto de las dimensiones especificadas en shape. Por ejemplo, un arreglo de shape (3, 4) tiene 3 * 4 = 12 elementos en total.

*   **dtype**: Describe el tipo de datos de los elementos en el arreglo (por ejemplo, int32, float64). Esto es importante, ya que NumPy usa tipos de datos fijos para optimizar el rendimiento y la memoria. Los datos de un mismo arreglo deben tener el mismo tipo, lo que permite a NumPy realizar operaciones rápidamente.



3.2 *Operaciones Matemáticas:*

Las operaciones matemáticas en NumPy están diseñadas para realizarse "elemento a elemento", es decir, cada operación se aplica a cada elemento del arreglo de manera individual. A continuación, se describen las operaciones matemáticas básicas y algunas funciones importantes:

* **Operaciones Aritméticas**: En NumPy, operaciones como suma (+), resta (-), multiplicación (*) y división (/) pueden aplicarse directamente a los arreglos. Cuando se realiza una operación entre dos arreglos de la misma forma, NumPy aplicará la operación elemento a elemento. Este tipo de operaciones se conoce como "broadcasting" y permite realizar cálculos eficientes sin necesidad de bucles explícitos.

* **Funciones Matemáticas Elementales**: NumPy proporciona una serie de funciones matemáticas que pueden aplicarse a cada elemento de un arreglo. Estas funciones incluyen:

  * Raíz Cuadrada (**np.sqrt**): Calcula la raíz cuadrada de cada elemento en el arreglo.
  * Exponencial (**np.exp**): Calcula el valor exponencial 𝑒ˣ
  para cada elemento.
  * Seno, Coseno, Tangente (**np.sin, np.cos, np.tan**): Calcula el valor de las funciones trigonométricas en radianes para cada elemento.
  * Logaritmo Natural (**np.log**): Calcula el logaritmo natural de cada elemento. Si un elemento es cero o negativo, NumPy devuelve un NaN o un valor infinito, ya que el logaritmo natural no está definido en esos casos.

  3.3 *Ejemplos:*

  Al combinar atributos y operaciones matemáticas, puedes analizar rápidamente las propiedades de los datos y realizar cálculos elementales. Veamos un ejemplo típico en el que se aplican tanto los atributos como las funciones básicas en un arreglo bidimensional.

In [1]:
import numpy as np

# Crear un arreglo bidimensional
a = np.array([[1, 2, 3], [4, 5, 6]])

# Atributos
print("Número de dimensiones (ndim):", a.ndim)  # Salida: 2 (bidimensional)
print("Forma del arreglo (shape):", a.shape)   # Salida: (2, 3)
print("Tamaño total (size):", a.size)          # Salida: 6
print("Tipo de dato de los elementos (dtype):", a.dtype)  # Salida: int32 o int64, según el sistema

Número de dimensiones (ndim): 2
Forma del arreglo (shape): (2, 3)
Tamaño total (size): 6
Tipo de dato de los elementos (dtype): int64


In [2]:
# Operaciones matemáticas
b = np.array([1, 2, 3])

# Suma de arreglos
print("\nSuma:", b + b)      # Salida esperada: [2 4 6]

# Raíz cuadrada de cada elemento
print("Raíz cuadrada:", np.sqrt(b))  # Salida esperada: [1. 1.41421356 1.73205081]

# Logaritmo de cada elemento
print("Logaritmo:", np.log(b))  # Salida esperada: [0. 0.69314718 1.09861229]



Suma: [2 4 6]
Raíz cuadrada: [1.         1.41421356 1.73205081]
Logaritmo: [0.         0.69314718 1.09861229]


4. **Indexación y Slicing en Arreglos.**

NumPy permite acceder a datos de manera rápida mediante índices y rangos de índices. Esta capacidad es esencial para manipular datos y trabajar con sub-arreglos.

4.1 *Indexación:*

Similar a las listas de Python, podemos acceder a elementos individuales de un arreglo utilizando índices. En arreglos unidimensionales, un solo índice es suficiente (a[i]), mientras que en arreglos multidimensionales, especificamos un índice para cada eje (a[i, j] para un arreglo 2D).

4.2 *Slicing:*

Con el slicing o corte, seleccionamos un rango de elementos de un arreglo utilizando la sintaxis inicio:fin. NumPy permite seleccionar subconjuntos de datos en un arreglo, aplicando slicing en varias dimensiones. La sintaxis básica es a[inicio:fin], y también puede incluir un paso (a[inicio:fin:paso]).


4.3 *Indexación Booleana:*

Permite seleccionar elementos del arreglo que cumplen una condición específica. Esto se logra utilizando comparaciones lógicas, como a > 2, que devuelve un arreglo de valores booleanos, indicando si cada elemento cumple la condición. Luego, aplicando este resultado al arreglo original (a[a > 2]), obtenemos solo los elementos que cumplen la condición.

4.4 *Ejemplos*:




In [3]:
import numpy as np

# Crear un arreglo bidimensional
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexación: acceso a un elemento específico
print("Elemento en la posición (1, 2):", a[1, 2])  # Salida esperada: 6

Elemento en la posición (1, 2): 6


In [5]:
# Slicing: seleccionar un subconjunto de filas y columnas
print("Segunda fila completa:", a[1, :])  # Salida esperada: [4 5 6]
print("Elementos de la primera y segunda fila, segunda y tercera columna:\n", a[:2, 1:])
# Salida esperada:
# [[2 3]
#  [5 6]]

Segunda fila completa: [4 5 6]
Elementos de la primera y segunda fila, segunda y tercera columna:
 [[2 3]
 [5 6]]


In [6]:
# Indexación Booleana: seleccionar elementos mayores que 5
print("Elementos mayores que 5:", a[a > 5])  # Salida esperada: [6 7 8 9]

Elementos mayores que 5: [6 7 8 9]


5. **Generación de Datos.**

NumPy ofrece varias funciones para generar arreglos con patrones y distribuciones predeterminadas:

5.1 *Rangos y Secuencias:*

+ **np.arange**(inicio, fin, paso): Genera un arreglo de números en un rango específico con un paso determinado. Es útil para crear secuencias uniformes de valores.
* **np.linspace**(inicio, fin, num): Genera un arreglo con num valores espaciados uniformemente entre inicio y fin, ideal para puntos en gráficos o interpolación.

5.2 *Arreglos de Ceros y Unos:*
* **np.zeros**(dimensiones): Genera un arreglo lleno de ceros en las dimensiones especificadas.
* **np.ones**(dimensiones): Genera un arreglo lleno de unos en las dimensiones especificadas.

5.3 *Números Aleatorios:*

* **np.random.rand**(dimensiones): Genera un arreglo de números aleatorios entre 0 y 1 con dimensiones especificadas.
* **np.random.randint**(bajo, alto, tamaño): Genera un arreglo de números enteros aleatorios en un rango específico [bajo, alto).

5.4 *Ejemplos:*

In [20]:
import numpy as np

# Crear una secuencia de números del 0 al 9
secuencia = np.arange(0, 10, 1)
print("Secuencia con np.arange:", secuencia)  # Salida esperada: [0 1 2 3 4 5 6 7 8 9]

Secuencia con np.arange: [0 1 2 3 4 5 6 7 8 9]


In [12]:
# Crear un arreglo de 5 valores espaciados uniformemente entre 0 y 1
espaciado = np.linspace(0, 1, 5)
print("Espaciado uniforme con np.linspace:", espaciado)  # Salida esperada: [0.   0.25 0.5  0.75 1.  ]

Espaciado uniforme con np.linspace: [0.   0.25 0.5  0.75 1.  ]


In [13]:
# Crear un arreglo de ceros con 2 filas y 3 columnas
ceros = np.zeros((2, 3))
print("Arreglo de ceros:\n", ceros)

Arreglo de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Crear un arreglo de números enteros aleatorios entre 1 y 10 de tamaño 3x3
aleatorios = np.random.randint(1, 10, (3, 3))
print("Arreglo de números aleatorios:\n", aleatorios)

Arreglo de números aleatorios:
 [[1 4 4]
 [4 3 8]
 [4 5 8]]


6. **Operaciones en Arreglos (Reducción).**
Las operaciones de reducción aplican una función que "reduce" un conjunto de valores a un solo resultado. Estas operaciones pueden calcularse a lo largo de un eje específico de un arreglo (por filas o columnas) o sobre el arreglo completo.

6.1 *Suma y Promedio:*

* **np.sum()**: Suma todos los elementos del arreglo. Con el parámetro axis, suma los elementos a lo largo de un eje específico.
* **np.mean()**: Calcula el promedio (media) de todos los elementos. Similar a sum, también admite axis para calcular el promedio por fila o columna.

6.2 *Mínimo y Máximo:*

* **np.min() y np.max()**: Encuentran el valor mínimo y máximo, respectivamente, de todos los elementos en el arreglo o a lo largo de un eje.
Producto:

* **np.prod()**: Calcula el producto de todos los elementos en el arreglo o en un eje específico.

6.3 *Ejemplos:*

In [21]:
import numpy as np

# Crear un arreglo bidimensional
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Suma de todos los elementos
print("Suma total de elementos:", np.sum(a))  # Salida esperada: 45

Suma total de elementos: 45


In [16]:
# Promedio de todos los elementos
print("Promedio de todos los elementos:", np.mean(a))  # Salida esperada: 5.0

Promedio de todos los elementos: 5.0


In [17]:
# Mínimo y máximo de todos los elementos
print("Mínimo de todos los elementos:", np.min(a))  # Salida esperada: 1
print("Máximo de todos los elementos:", np.max(a))  # Salida esperada: 9

Mínimo de todos los elementos: 1
Máximo de todos los elementos: 9


In [18]:
# Suma por filas y columnas
print("Suma por filas:", np.sum(a, axis=1))  # Salida esperada: [6 15 24]
print("Suma por columnas:", np.sum(a, axis=0))  # Salida esperada: [12 15 18]

Suma por filas: [ 6 15 24]
Suma por columnas: [12 15 18]


In [19]:
# Producto de todos los elementos
print("Producto de todos los elementos:", np.prod(a))  # Salida esperada: 362880

Producto de todos los elementos: 362880


7. **Manipulación de la Forma de Arreglos.**

A menudo, cuando se manejan datos en arreglos, necesitamos reorganizarlos o cambiar su forma para ajustarse a ciertas operaciones o visualizaciones. NumPy facilita esta manipulación mediante varias funciones:

* **reshape()**:
Permite cambiar la forma de un arreglo sin alterar sus datos. Por ejemplo, podemos cambiar un arreglo de 1D (como [1, 2, 3, 4]) a 2D (como [[1, 2], [3, 4]]). Sin embargo, el número total de elementos debe coincidir, es decir, un arreglo de tamaño 4 solo puede convertirse en una forma compatible con 4 elementos, como (2,2).

* **ravel() y flatten()**:
Ambas funciones transforman un arreglo multidimensional en uno unidimensional. ravel devuelve una vista (referencia) del arreglo original, lo que significa que si se modifica el arreglo resultante, también se cambia el original. flatten, en cambio, crea una copia independiente.

* **transpose()**:
Cambia el orden de los ejes de un arreglo, lo que es especialmente útil en álgebra lineal y operaciones en matrices. Por ejemplo, en un arreglo 2D, transpose intercambia las filas y las columnas.

7.1 *Ejemplos:*

In [23]:
import numpy as np

# Crear un arreglo unidimensional
a = np.array([1, 2, 3, 4, 5, 6])

# Cambiar la forma del arreglo a 2x3
b = a.reshape((2, 3))
print("Arreglo con forma 2x3:\n", b)

Arreglo con forma 2x3:
 [[1 2 3]
 [4 5 6]]


In [24]:
# Aplanar el arreglo a un solo vector
c = b.ravel()
print("Arreglo aplanado:", c)

Arreglo aplanado: [1 2 3 4 5 6]


In [25]:
# Transponer un arreglo 2D
d = np.array([[1, 2, 3], [4, 5, 6]])
print("Arreglo original:\n", d)
print("Arreglo transpuesto:\n", d.transpose())

Arreglo original:
 [[1 2 3]
 [4 5 6]]
Arreglo transpuesto:
 [[1 4]
 [2 5]
 [3 6]]


8. **Tablas de Datos.**

Los arreglos bidimensionales en NumPy pueden representar tablas de datos, donde cada fila es un registro (ej., una observación o muestra) y cada columna representa una variable (ej., una característica o atributo). NumPy permite realizar cálculos y análisis sobre estos datos de manera eficiente.

8.1 *Operaciones en Tablas:*

Las operaciones en tablas pueden aplicarse por filas o columnas usando el parámetro axis. Por ejemplo, para calcular el promedio de cada columna, usamos np.mean(data, axis=0).

8.2 *Selección de Subconjuntos de Tablas:*

Usando la indexación y el slicing, podemos seleccionar partes específicas de la tabla, como todas las filas de una columna específica, o un subconjunto de filas y columnas.

8.3 *Análisis Estadístico:*

NumPy ofrece varias funciones estadísticas que facilitan el análisis de datos en formato tabular, como np.mean, np.median, np.std (desviación estándar), np.var (varianza), entre otras. Estas funciones son útiles para resumir y entender las características de los datos en cada columna.

8.4 *Ejemplos:*

In [26]:
# Crear un arreglo bidimensional que representa una tabla de datos
data = np.array([[5.1, 3.5, 1.4, 0.2],
                 [4.9, 3.0, 1.4, 0.2],
                 [6.7, 3.1, 4.4, 1.4],
                 [5.9, 3.2, 4.8, 1.8]])

# Seleccionar la primera columna (todas las filas)
print("Primera columna:", data[:, 0])

Primera columna: [5.1 4.9 6.7 5.9]


In [27]:
# Calcular el promedio de cada columna
print("Promedio de cada columna:", np.mean(data, axis=0))

Promedio de cada columna: [5.65 3.2  3.   0.9 ]


In [28]:
# Calcular la desviación estándar de cada columna
print("Desviación estándar de cada columna:", np.std(data, axis=0))

Desviación estándar de cada columna: [0.71239034 0.18708287 1.60623784 0.71414284]


In [29]:
# Seleccionar un subconjunto de la tabla (las primeras dos filas y dos primeras columnas)
print("Subconjunto de la tabla:\n", data[:2, :2])

Subconjunto de la tabla:
 [[5.1 3.5]
 [4.9 3. ]]


9. **Conclusión.**

A lo largo de este tutorial, exploramos las funcionalidades esenciales de la librería NumPy, desde la creación de arreglos y manipulación de datos hasta la aplicación de operaciones avanzadas. NumPy es una herramienta fundamental en el trabajo con datos en Python debido a su eficiencia y capacidad para manejar grandes volúmenes de datos, especialmente en aplicaciones científicas y de ingeniería. Su uso optimiza el procesamiento de datos y permite realizar cálculos complejos de manera mucho más rápida que con estructuras de datos tradicionales de Python, como las listas.

Al aprender sobre operaciones básicas, manipulación de formas y el trabajo con tablas de datos, obtuviste una base sólida para tareas como análisis de datos, interpolación, y futuras aplicaciones en álgebra lineal y estadísticas. Practicar con estos conceptos y aplicar NumPy en proyectos o problemas específicos te ayudará a familiarizarte aún más con sus capacidades y descubrir nuevas aplicaciones prácticas.

10. **Fuentes adicionales para aprender más sobre NumPy.**

Para continuar tu aprendizaje y profundizar en el uso de NumPy, puedes explorar las siguientes fuentes:


1.   **Documentación Oficial de NumPy**: La documentación oficial es el mejor lugar para obtener información detallada sobre cada función y utilidad de NumPy. También incluye ejemplos y guías de uso. -> [NumPy Documentation](https://numpy.org/doc/)
2.   **NumPy User Guide**: Esta guía, dentro de la documentación oficial, es muy útil para principiantes e intermedios, y cubre temas básicos y avanzados. -> [NumPy User Guide](https://numpy.org/doc/stable/user/)
3.   **Python Data Science Handbook de Jake VanderPlas**: Este libro es una excelente introducción práctica a NumPy y otras librerías de Python enfocadas en ciencia de datos, como pandas y Matplotlib. -> [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)
4.   **Khan Academy y Coursera**: En estas plataformas, encontrarás cursos de introducción al álgebra lineal y estadística, que pueden complementar el conocimiento en NumPy al entender mejor cómo usarlo en operaciones matemáticas.
5.  **Tutoriales de NumPy en Jupyter Notebooks**: Existen numerosos tutoriales interactivos en plataformas como Google Colab o [Kaggle](https://www.kaggle.com/) que permiten practicar directamente en un entorno Jupyter Notebook.
